
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-serviceaccount-kubetrail-io-v1beta1-token
  failurePolicy: Fail
  name: mtoken.kb.io
  rules:
  - apiGroups:
    - serviceaccount.kubetrail.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tokens
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-serviceaccount-kubetrail-io-v1beta1-token
  failurePolicy: Fail
  name: vtoken.kb.io
  rules:
  - apiGroups:
    - serviceaccount.kubetrail.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tokens
  sideEffects: None
